### ISSUE TITLE
client.player.isPlaying(message) always returns false

### ISSUE THREAD

**Issue by SathvikKS** [SushiBtw/discord-music-player#134]
**Bug Description**
isPlaying() always returns false even if the song is playing, as result of which the play command always plays the song entered and does not add to queue while playing the previous song

**Attachments**
the code:
![image](https://user-images.githubusercontent.com/31741267/118969841-31153c00-b98b-11eb-9e92-67f526893475.png)

console output
![image](https://user-images.githubusercontent.com/31741267/118969910-425e4880-b98b-11eb-8e6e-729ea764c3d0.png)

First false makes sense. However, the second play <songname> was used while the first song was still playing, so it is expected to return true.

**Comment by Bowedyapper** [comment]
I have managed to reproduce this issue, if you are using the package within a command file, make sure to add the player variables above the module definition like so:

![image](https://user-images.githubusercontent.com/40412992/119281765-d4d24680-bc2e-11eb-8d16-39c031dc6925.png)

Otherwise the player object will just be overwritten everytime you run the command and the queue will no longer exist.

**Comment by SpeckyYT** [comment]
You're creating a new player on each command file, which won't be connected to the other files.
Be sure to setup the player on boot-up globally or into the client object.
