### ISSUE TITLE
[BUG] 'Now playing' messages from other servers

### ISSUE THREAD

**Issue by EclipseGame18** [SushiBtw/discord-music-player#238]
**Bug Description**
I got a 'now playing' message with a song I didn't add form another server.

**Expected Result**
other queues from different servers should not interfere.

**Attachments**
If applicable, add screenshots to help explain your problem. (see screenshot)

**Versioning:**
- OS: Windows Discord, Heroku hosting
- Node Version latest
- Module Version latest
![Screenshot (50)_LI](https://user-images.githubusercontent.com/68092869/139631496-e415bfa8-e9d5-41c7-bea1-a3b69e51619b.jpg)

**Comment by MeridianGH** [comment]
We need your code to be able to help you out.

The issue is most likely that `Player#songChanged` fires for every changed song across all servers. However, it returns a queue that you should be able to use to identify the server.
I'd recommend setting a text channel for every queue, such as the last text channel that was used to execute a command and using said text channel to send a now-playing embed. I'm using `queue.lastTextChannel` for example.

**Comment by EclipseGame18** [comment]
this is the code:
```
.on('songChanged', (queue, newSong, oldSong) =>{
	const embed = new MessageEmbed()
	.setTitle('New Song:')
	.setDescription(`\`${oldSong}\` has finished, now playing: [${newSong}](${newSong.url})!`)
	.setThumbnail(`${newSong.thumbnail}`)
	.setFooter(`Requested by: ${requestedBy}`)
	.setColor('#6CFFD9');
	lastMessage.channel.send({embeds: [embed]})
	return;
```

**Comment by SushiBtw** [comment]
You are sending that via `<lastMessage>`, what's that?

**Comment by EclipseGame18** [comment]
The lastmessage is a var:

Var lastmessage = null

.on("messagecreate"...){
Lastmessage = message. channel.send
}

**Comment by SushiBtw** [comment]
Then you send the songChanged embed to the last message channel. Change it.
