### ISSUE TITLE
queue.songs[i] always returns the first song I queued, but plays normally

### ISSUE THREAD

**Issue by Imisuuu** [SushiBtw/discord-music-player#271]
**Bug Description**
Every time I try to get a song name using `queue.songs[i].name` I get the same value every time. 
This is my play command code:
```js
if(command === 'play' || command === 'p') { //play
        let queue = client.player.createQueue(message.guild.id);
        
        await queue.join(message.member.voice.channel);
        let song = await queue.play(args.join(' ')).catch(_ => {
            if(!guildQueue)
                queue.stop();
        });
        console.log(queue.songs[i]);
        songName = queue.songs[i].name;
        songDuration = queue.songs[i].duration;
        message.channel.send(`🎶Dodano do **SonataQueue[ ${songName} ]**` +  "(`" + songDuration + "`)!")
        i += 1;
    }   
```

**Versioning:**
- OS: Windows 11
- Node Version: 16.13.1
- Module Version: 8.3.1

**Comment by SpeckyYT** [comment]
1) why are you doing `queue.songs[i]` instead of using the `song` item you already have?
2) if you ignore 1, where is `i` defined?
3) if you ignore 2, why are you indexing an array of variable length in time if you could just get the last item of the array?
4) if you ignore 3, why are you declaring `songName` and `songDescription` globally?

**Comment by Imisuuu** [comment]
That was a skill issue, thanks :)
