### ISSUE TITLE
[BUG] providing links to play doesn't work

### ISSUE THREAD

**Issue by warior456** [SushiBtw/discord-music-player#276]
when trying to play a song if you give it a link it fails

use your play command with a link instead of a name to the song

error:
 TypeError: Cannot read properties of undefined (reading 'response'): There was an Unknown Error.
    at H:\discordbot\mrdia-main\node_modules\discord-music-player\dist\managers\Queue.js:187:23
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

- OS:windows 10

this wasn't yesterday so it might be to do with youtube

**Comment by joshbrucker** [comment]
It looks like the problem lies in [youtubei](https://github.com/SuspiciousLookingOwl/youtubei). More specifically, the response model they get back from YouTube has changed, so they very recently implemented a fix to handle it properly.

I just created a PR (https://github.com/SushiBtw/discord-music-player/pull/277) to update the youtubei dependency.

**Comment by SushiBtw** [comment]
Thanks @joshbrucker for the PR. I will be updating npm later today.
