### ISSUE TITLE
[BUG] TypeError: setting 'data')

### ISSUE THREAD

**Issue by Pqoh** [SushiBtw/discord-music-player#282]
**Bug Description**
When I put the bot to play a specific playlist (only with it), it returns this error: 

**Reproduction Steps**
1. Play a playlist.
2. Observe the result.

**Expected Result**
play the playlist normally 

**Attachments**
This error:
![Screenshot_20220603-113623_Chrome](https://user-images.githubusercontent.com/48698601/171876490-1e7bd0d5-42f6-40c6-b2d2-715130e3e4eb.png)

**Versioning:**
- OS: [e.g. Ubuntu 18.04]
- Node Version [e.g. v16.6.0]
- Module Version [e.g v6.2.0]

**Additional Comments**
Playlist: https://open.spotify.com/playlist/6ebTlIkCABdud4wMeNW2UU?si=SElPo6DJT1OWQxA-JGI4YQ&utm_source=copy-link

**Comment by joshbrucker** [comment]
I'm not entirely sure what action on your side caused this error, because I'm able to play that playlist fine on my music bot.

But your trace did help me identify the bug throwing the unknown error. I've fixed it in [this PR](https://github.com/SushiBtw/discord-music-player/pull/283) that edits one of the conditionals.

**Comment by warior456** [comment]
@SushiBtw merge?

**Comment by SushiBtw** [comment]
Will merge this today.

@warior456 @joshbrucker
